version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/.env.example:/app/.env

  kiosk-app:
    build:
      context: ./kiosk-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./kiosk-app/src:/app/src
      - ./kiosk-app/package.json:/app/package.json

  admin-app:
    build:
      context: ./admin-app
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./admin-app/src:/app/src
      - ./admin-app/package.json:/app/package.json

  supabase:
    image: supabase/postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data: